spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer
  application:
    name: registration-service
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
